<a href="https://www.kaggle.com/code/paigecrossley/topcoder-genetic-data-classification-challenge?scriptVersionId=130996097" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# imports 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import mean_absolute_error


# import data
X = pd.read_csv('/kaggle/input/genetic-data-classification-practice-challenge/train.csv',header=None)
test_X = pd.read_csv('/kaggle/input/genetic-data-classification-practice-challenge/test_x.csv',header=None)

In [2]:
X.head()

0         1         2         3          4      5         6         7      \
0    0.0  3.801873  5.025591  6.404150   9.564754    0.0  9.997688  1.025241   
1    0.0  2.988103  1.811471  5.763507   8.604753    0.0  7.335855  0.787850   
2    0.0  1.913914  3.568069  6.498854   9.865512    0.0  7.664440  1.830012   
3    0.0  1.786638  1.768460  5.662160  10.360353    0.0  7.294281  1.056098   
4    0.0  4.122805  2.939922  6.730137   9.508001    0.0  6.959306  0.845109   

   8      9      ...     20522      20523     20524      20525      20526  \
0    0.0    0.0  ...  8.507347   9.849333  8.184360   9.796564  11.607552   
1    0.0    0.0  ...  8.986857  10.444663  1.824849  10.053587  11.873652   
2    0.0    0.0  ...  8.969893  10.653248  3.042679  11.449443  10.559874   
3    0.0    0.0  ...  7.907323  10.123358  1.389016   9.964891  11.407300   
4    0.0    0.0  ...  9.459323  10.705149  6.782736  10.622290  11.136222   

       20527      20528      20529     20530  20531  
0  10.456272   9.949412   5.980037  0.000000    0.0  
1  10.603654   9.608950   5.026884  0.000000    1.0  
2  10.351812   9.446593  10.168559  0.888928    1.0  
3  10.644857   9.912535   8.256968  0.000000    1.0  
4  10.787837  10.416871   8.318724  0.000000    0.0  

[5 rows x 20532 columns]

In [3]:
# Check for missing or na values

cols_with_missing = [col for col in X.columns if X[col].isnull().any()]
cols_with_na = [col for col in X.columns if X[col].isna().any()]

print(cols_with_missing, cols_with_na)

[] []


In [4]:
np.shape(X)

(560, 20532)

In [5]:
# Get target column

y = X[20531]
X.drop([20531], axis=1, inplace=True)

In [6]:
X.head()

0         1         2         3          4      5         6         7      \
0    0.0  3.801873  5.025591  6.404150   9.564754    0.0  9.997688  1.025241   
1    0.0  2.988103  1.811471  5.763507   8.604753    0.0  7.335855  0.787850   
2    0.0  1.913914  3.568069  6.498854   9.865512    0.0  7.664440  1.830012   
3    0.0  1.786638  1.768460  5.662160  10.360353    0.0  7.294281  1.056098   
4    0.0  4.122805  2.939922  6.730137   9.508001    0.0  6.959306  0.845109   

   8      9      ...     20521     20522      20523     20524      20525  \
0    0.0    0.0  ...  5.919628  8.507347   9.849333  8.184360   9.796564   
1    0.0    0.0  ...  7.156478  8.986857  10.444663  1.824849  10.053587   
2    0.0    0.0  ...  5.991102  8.969893  10.653248  3.042679  11.449443   
3    0.0    0.0  ...  5.941165  7.907323  10.123358  1.389016   9.964891   
4    0.0    0.0  ...  6.704111  9.459323  10.705149  6.782736  10.622290   

       20526      20527      20528      20529     20530  
0  11.607552  10.456272   9.949412   5.980037  0.000000  
1  11.873652  10.603654   9.608950   5.026884  0.000000  
2  10.559874  10.351812   9.446593  10.168559  0.888928  
3  11.407300  10.644857   9.912535   8.256968  0.000000  
4  11.136222  10.787837  10.416871   8.318724  0.000000  

[5 rows x 20531 columns]

In [7]:
# Break into validation and training data

X_train, X_valid, y_train, y_valid = train_test_split(X, y,train_size=0.8, test_size=0.2,random_state=0)

In [8]:
# Define a random forest model

rf_model = RandomForestClassifier(random_state=1)
rf_model.fit(X_train, y_train)
rf_val_predictions = rf_model.predict(X_valid)
rf_val_mae = mean_absolute_error(rf_val_predictions, y_valid)

print("Validation MAE for Random Forest Model: {:,.0f}".format(rf_val_mae))

Validation MAE for Random Forest Model: 0


In [9]:
# Fit the model and obtain probabilities

model = RandomForestClassifier(random_state=1)
model.fit(X, y)
preds_test = model.predict(test_X)
preds_prob_test = model.predict_proba(test_X)

In [10]:
np.shape(preds_prob_test)

(241, 5)

In [11]:
print(preds_prob_test)

[[0.02 0.02 0.92 0.03 0.01]
 [0.02 0.04 0.89 0.05 0.  ]
 [0.22 0.06 0.03 0.64 0.05]
 ...
 [0.05 0.03 0.03 0.03 0.86]
 [0.   0.03 0.91 0.04 0.02]
 [0.94 0.01 0.   0.04 0.01]]


In [12]:
print(preds_test)

[2. 2. 3. 0. 3. 2. 1. 1. 3. 2. 0. 3. 1. 0. 0. 3. 0. 1. 0. 1. 0. 4. 4. 4.
 0. 3. 4. 3. 4. 0. 3. 0. 0. 1. 3. 1. 1. 0. 0. 1. 0. 1. 4. 2. 2. 0. 2. 2.
 4. 3. 0. 3. 0. 0. 0. 1. 0. 0. 2. 3. 3. 1. 4. 2. 4. 0. 0. 4. 3. 4. 0. 1.
 3. 0. 1. 3. 0. 4. 0. 1. 0. 0. 0. 0. 0. 4. 1. 3. 2. 0. 2. 0. 3. 0. 4. 4.
 4. 1. 1. 4. 4. 3. 1. 3. 0. 2. 3. 1. 3. 4. 3. 0. 3. 1. 1. 4. 3. 2. 1. 3.
 4. 0. 3. 0. 0. 1. 0. 2. 0. 1. 2. 0. 4. 2. 0. 0. 1. 0. 0. 1. 3. 3. 0. 0.
 2. 0. 4. 4. 0. 0. 1. 4. 2. 1. 3. 1. 2. 3. 3. 1. 2. 2. 4. 0. 4. 0. 3. 3.
 3. 0. 1. 1. 2. 0. 0. 0. 4. 4. 4. 4. 3. 0. 3. 3. 4. 1. 1. 0. 1. 3. 2. 0.
 0. 4. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 4. 4. 4. 2. 0. 0. 4. 0. 0. 3. 2. 0.
 4. 0. 1. 1. 1. 0. 1. 0. 4. 0. 0. 4. 3. 3. 0. 1. 2. 0. 3. 2. 4. 0. 4. 2.
 0.]


In [13]:
# Turn the probabilities into a matrix and add it to the test df for submission

prob_matrix = np.asmatrix(preds_prob_test)

solutions = pd.concat([test_X, pd.DataFrame(prob_matrix)], axis=1)

In [14]:
solutions.head()

0         1         2         3          4      5         6         7      \
0    0.0  3.223716  3.027490  9.173387  10.057410    0.0  7.236426  0.600745   
1    0.0  1.624335  2.880039  7.849242   9.961128    0.0  7.426315  0.000000   
2    0.0  4.403799  5.650767  6.237965   9.928791    0.0  8.193653  0.729357   
3    0.0  3.998728  3.537644  6.336483  10.198433    0.0  6.605121  0.438825   
4    0.0  2.352504  2.541366  6.823495  10.259614    0.0  6.326269  0.000000   

   8      9      ...      20526      20527     20528     20529  20530  0      \
0    0.0    0.0  ...  11.991256  10.228650  9.914923  3.950730    0.0   0.02   
1    0.0    0.0  ...  12.131397  10.235763  9.007652  2.728965    0.0   0.02   
2    0.0    0.0  ...  11.474755   9.415547  9.388187  1.860605    0.0   0.22   
3    0.0    0.0  ...  11.729030  10.140983  9.519872  8.503579    0.0   0.95   
4    0.0    0.0  ...  12.356075   9.423801  9.575008  5.176171    0.0   0.11   

   1      2      3      4      
0   0.02   0.92   0.03   0.01  
1   0.04   0.89   0.05   0.00  
2   0.06   0.03   0.64   0.05  
3   0.01   0.01   0.03   0.00  
4   0.01   0.01   0.85   0.02  

[5 rows x 20536 columns]

In [15]:
solutions.to_csv('solution.csv')